### ISSUE TITLE
Some of the missing topics in advance javascript

### ISSUE THREAD

**Issue by aayush1408** [summer-skills/curriculum#1]
- Strong understanding of callbacks
- Basic understanding of async await
- Event bubbling and delegation
- Pass by Value vs Pass by reference
- Hoisting in Javascript
- Regular Expressions
- Event Loop 
- Prototypal inheritance
- Recursion
- Coercion in Javascript
- Some basic understanding of v8

**Comment by itaditya** [comment]
All this looks great.

Are you sure we should include *Some basic understanding of v8*

**Comment by itaditya** [comment]
* About recursion, I don't think it's something we should include. 

Because our main focus is on **getting students job ready** and I haven't really used recursion in my frontend or backend code till this point.

Recursion might be useful but in some particular cases, so let's leave that for now

**Comment by aayush1408** [comment]
Yes you have a point, Recusion and Understanding of v8 can be excluded out.

**Comment by itaditya** [comment]
Closing this issue, reopen if needed
